### ISSUE TITLE
Pip install doesn't pull in dependencies

### ISSUE THREAD

**Issue by addisonklinke** [Ars-Linguistica/mlconjug3#514]
**Describe the bug**

Pip install doesn't pull in dependencies

**To Reproduce**

```
pip install mlconjug3
python -c "import mlconjug3"
```

**Expected behavior**

Installation includes all dependencies so import can work immediately

**Actual behavior**

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/addisonklinke/venv/test/lib/python3.12/site-packages/mlconjug3/__init__.py", line 39, in <module>
    from .constants import *
  File "/Users/addisonklinke/venv/test/lib/python3.12/site-packages/mlconjug3/constants/__init__.py", line 1, in <module>
    from .constants import *
  File "/Users/addisonklinke/venv/test/lib/python3.12/site-packages/mlconjug3/constants/constants.py", line 1, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

Then after running `pip install setuptools` as recommended in this [answer](https://stackoverflow.com/a/10538412/7446465)

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/addisonklinke/venv/test/lib/python3.12/site-packages/mlconjug3/__init__.py", line 39, in <module>
    from .constants import *
  File "/Users/addisonklinke/venv/test/lib/python3.12/site-packages/mlconjug3/constants/__init__.py", line 1, in <module>
    from .constants import *
  File "/Users/addisonklinke/venv/test/lib/python3.12/site-packages/mlconjug3/constants/constants.py", line 5, in <module>
    from yaml import load, dump
ModuleNotFoundError: No module named 'yaml'
```

and so on through the entire [list of requirements](https://github.com/Ars-Linguistica/mlconjug3/blob/10b95c6f91f5f27d27f5a0872a7889baf9a09b66/setup.py#L24-L32) in `setup.py` 

**Desktop:**
 - macOS 14.4.1
 - Python 3.12.2
 - pip 24.0

**Comment by addisonklinke** [comment]
@SekouDiaoNlp thanks for the excellent project! Curious if you or any of the other contributors have bandwidth to look into this one?

**Comment by joprice** [comment]
Even after manually installing the libs, I get the error "An error occurred: Can't get attribute 'Log' on <module 'sklearn.linear_model._sgd_fast'". This seems like an interesting project, but unfortunately unusable if the deps aren't configured to work with standard tooling.

**Comment by spmcn** [comment]
My solution was use Python version prior to 12 (I used 3.11.9), and then install numpy as an earlier version (I did 1.26.4), and it seemed to work:

pip install mlconjug3 "numpy<2.0.0"

The devs will have to modify their requirements.txt to make the fix.
